### PR TITLE
use only valid bank countries and corresponding IBAN in ingested cont…

### PR DESCRIPTION
**Pull request by volkodava**
Hi team,

In this PR we fix data incompatibility issue - Bank country should always have corresponding IBAN, otherwise payment won't be able to be created. Change was tested and verified in test environment.

### CODE REVIEW

**Review by eliasnogueira — CHANGES_REQUESTED** [review]
Please look at the general comment I added to not restrict the country + IBAN combination

**Comment by volkodava** [comment]
> Please look at the general comment I added to not restrict the country + IBAN combination

done

**Comment by volkodava** [comment]
> @volkodava Could you please create a property to control when the combination of country + IBAN is necessary?
> 
> **Proposed change**
> 
>     * creation of a new property like `contacts.sanctioned.countries`
> 
>     * usage of private methods to determine if the country + IBAN will be generated by faker or by a list of valid combinations for the sanctioned countries feature
> 
> 
> **Why the proposed change** We don't know if the restriction of four (4) countries + IBAN for contacts will affect any other team, and like it is a specific feature for payments the best way to avoid issues is through isolation.
> 
> **What it would looks like** For the local run an additional argument `-Dcontacts.sanctioned.countries=true` will be added.
> 
> For the execution using the pipeline the `ADDITIONAL_ARGUMENTS` will have the value `-Dcontacts.sanctioned.countries=true`

done

**Comment by eliasnogueira** [comment]
@volkodava I believe we can simplify using something like the example below, that is getting the list of countries based on the property and generating the correct iban for it.

the only problem is that the following countries would be excluded from the generation, as those aren't supported in the Iban4j
```
From contacts
AR, AU, CA, CN, CO, EC, EG, ET, HN, HK, IN, ID, JM, MY, MX, MA, NA, NZ, RU, SG, ZA, LK, TH, UG, US, ZW

From payments
AU, CA, CV, HK, IN, JP, EU, SG, US, ZA
```

Example
```java
public class Example {

    private static final List<String> SUPPORTED_SANCTIONED_COUNTRIES =
            asList("AE", "AU", "BR", "CA", "CN", "GB", "HK", "IN", "JO", "JP", "NL", "RU", "SG", "US", "ZA");
    private static final List<String> SUPPORTED_CONTACTS_COUNTRIES =
            asList("AR", "AU", "AT", "BE", "BR", "CA", "CN", "CO", "HR", "CZ", "DK", "EC", "EG", "ET", "FR",
                    "DE", "GR", "HN", "HK", "HU", "IN", "ID", "IE", "IT", "JM", "MY", "MX", "MA", "NA", "NL", "NZ",
                    "NO", "PL", "PT", "RU", "SN", "SG", "ZA", "ES", "LK", "SE", "TH", "TR", "UG", "AE", "GB", "US", "ZW");

    public static void main(String[] args) {
        List<String> countriesToUse = GlobalProperties.getInstance().getBoolean(PROPERTY_CONTACTS_SANCTIONED_COUNTRIES)
                ? SUPPORTED_SANCTIONED_COUNTRIES : SUPPORTED_CONTACTS_COUNTRIES;
        
        Iban iban = validIBanBasedOnSupportedCountries(countriesToUse);

        iban.getCountryCode(); // return the country code
        iban; // return the IBAN
    }

    private static Iban validIBanBasedOnSupportedCountries(List<String> countriesToUse) {
        String countryToGenerateIban = countriesToUse.get(new Random().nextInt(countriesToUse.size()));

        return new Iban.Builder().countryCode(CountryCode.valueOf(countryToGenerateIban)).buildRandom();
    }
}
```

**Comment by volkodava** [comment]
> @volkodava I believe we can simplify using something like the example below, that is getting the list of countries based on the property and generating the correct iban for it.
> 
> the only problem is that the following countries would be excluded from the generation, as those aren't supported in the Iban4j
> 
> ```
> From contacts
> AR, AU, CA, CN, CO, EC, EG, ET, HN, HK, IN, ID, JM, MY, MX, MA, NA, NZ, RU, SG, ZA, LK, TH, UG, US, ZW
> 
> From payments
> AU, CA, CV, HK, IN, JP, EU, SG, US, ZA
> ```
> 
> Example
> 
> ```java
> public class Example {
> 
>     private static final List<String> SUPPORTED_SANCTIONED_COUNTRIES =
>             asList("AE", "AU", "BR", "CA", "CN", "GB", "HK", "IN", "JO", "JP", "NL", "RU", "SG", "US", "ZA");
>     private static final List<String> SUPPORTED_CONTACTS_COUNTRIES =
>             asList("AR", "AU", "AT", "BE", "BR", "CA", "CN", "CO", "HR", "CZ", "DK", "EC", "EG", "ET", "FR",
>                     "DE", "GR", "HN", "HK", "HU", "IN", "ID", "IE", "IT", "JM", "MY", "MX", "MA", "NA", "NL", "NZ",
>                     "NO", "PL", "PT", "RU", "SN", "SG", "ZA", "ES", "LK", "SE", "TH", "TR", "UG", "AE", "GB", "US", "ZW");
> 
>     public static void main(String[] args) {
>         List<String> countriesToUse = GlobalProperties.getInstance().getBoolean(PROPERTY_CONTACTS_SANCTIONED_COUNTRIES)
>                 ? SUPPORTED_SANCTIONED_COUNTRIES : SUPPORTED_CONTACTS_COUNTRIES;
>         
>         Iban iban = validIBanBasedOnSupportedCountries(countriesToUse);
> 
>         iban.getCountryCode(); // return the country code
>         iban; // return the IBAN
>         iban.getBankCode(); // return the BIC
>     }
> 
>     private static Iban validIBanBasedOnSupportedCountries(List<String> countriesToUse) {
>         String countryToGenerateIban = countriesToUse.get(new Random().nextInt(countriesToUse.size()));
> 
>         return new Iban.Builder().countryCode(CountryCode.valueOf(countryToGenerateIban)).buildRandom();
>     }
> }
> ```

done

**Pull request merged**
